version: '3'

services:
  aghilpadash_postgresql:
    image: postgres:latest
    container_name: aghilpadash_postgresql
    volumes:
      - aghilpadash_postgresql:/var/lib/postgresql/data
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - aghilpadash_network

volumes:
  aghilpadash_postgresql:
    external: true
networks:
  aghilpadash_network:
    external: true
